const data = [
  {
    id: 1,
    courseName: "WordPress",
    title: "This Course is for wordpress Developer",
    price: 300,
    duration: "2h 10min",
    img: "https://cdn6.f-cdn.com/contestentries/1715316/40182000/5e173e4e34867_thumb900.jpg",
  },
  {
    id: 2,
    courseName: "Js Developer",
    title: "This Course is for Js Developer",
    price: 350,
    duration: "3h 10min",
    img: "https://www.learn-js.org/static/img/logos/learn-js.org.png",
  },
  {
    id: 3,
    courseName: "React",
    title: "This Course is for React Developer",
    price: 450,
    duration: "7h 10min",
    img: "https://blog.wildix.com/wp-content/uploads/2020/06/react-logo.jpg",
  },
  {
    id: 4,
    courseName: "Django",
    title: "This Course is for Django Developer",
    price: 450,
    duration: "8h 10min",
    img: "https://i.ytimg.com/vi/u1FR1nZ6Ng4/maxresdefault.jpg",
  },
  {
    id: 5,
    courseName: "Laravel",
    title: "This Course is for Laravel Developer",
    price: 350,
    duration: "7h 10min",
    img: "https://y4h9p9e3.stackpathcdn.com/wp-content/uploads/laravel_loadsys.png",
  },
  {
    id: 6,
    courseName: "PHP Developer",
    title: "This Course is for PHP Developer",
    price: 250,
    duration: "5h 10min",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/PHP-logo.svg/1200px-PHP-logo.svg.png",
  },
  {
    id: 7,
    courseName: "Codeigniter  ",
    title: "This Course is for Codeigniter Developer",
    price: 350,
    duration: "6h 10min",
    img: "https://cdn.pngsumo.com/how-to-watermark-images-using-codeigniter-php-framework-codeigniter-png-500_500.jpg",
  },
  {
    id: 8,
    courseName: "Flask  ",
    title: "This Course is for Flask Developer",
    price: 550,
    duration: "4h 10min",
    img: "https://i.ytimg.com/vi/Qr4QMBUPxWo/maxresdefault.jpg",
  },
  {
    id: 9,
    courseName: "HTML & CSS",
    title: "This Course is for HTML & CSS Designer",
    price: 350,
    duration: "7h 10min",
    img: "https://www.seekpng.com/png/full/222-2229726_intro-to-html-css-html-css-icon.png",
  },
];
